### ISSUE TITLE
Possible ArrayAccess

### ISSUE THREAD

**Issue by OddGreg** [opulencephp/environments#1]
@opulencephp 

What is your stance on adding `implements \ArrayAccess` to the `Environment` class?

ie: `$environment['DB_NAME'] = 'blah'` and `$db_name = $environment['DB_NAME']` etc.

**Comment by opulencephp** [comment]
I'm not opposed at all.  Good idea.

**Comment by OddGreg** [comment]
Alright, I work it up and issue a PR when ready.
